name: Patient Service Pipeline

on:
  push:
    branches:
      - patient-service

env:
  DOCKER_IMAGE_NAME: joebeanzz123/patient-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG .
          docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
          # Also push the same image as 'latest'
          docker tag $DOCKER_IMAGE_NAME:$IMAGE_TAG $DOCKER_IMAGE_NAME:latest
          docker push $DOCKER_IMAGE_NAME:latest
